# Generated by Django 5.0.7 on 2024-07-31 06:12

import django.core.validators
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(default=registration.models.generate_voter_id, editable=False, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='First name must contain only alphabets.', regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Last name must contain only alphabets.', regex='^[a-zA-Z]+$')])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be 6 digits.', regex='^\\d{6}$')])),
                ('date_of_birth', models.DateField(validators=[registration.models.validate_age])),
                ('contact', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact must be 10 digits.', regex='^\\d{10}$')])),
            ],
        ),
    ]
